name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.0
    - name: Install dependencies
      run: yarn
    - name: Lint
      run: yarn eslint ./src
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0
    - name: Install dependencies
      run: yarn
    - name: Test
      run: yarn test

