# This is a basic workflow to help you get started with Actions

name: CD

# Run when tags are pushed
on:
  push:
    tags:
    - '*'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.0
    - name: Install dependencies
      run: yarn --network-concurrency 1
    - run: CI=false yarn build
    - uses: nwtgck/actions-netlify@v1.1.5
      with:
        publish-dir: build
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}      
